name: Lint test and deploy on push
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        
      - name: cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: install Dependencies
        run: npm install
      - name: lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: Test code
        id: run-test
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deployement
        run: echo "Deploying"
      - name: Get build Artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Output Contents
        run: ls

  report: 
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong" 
          echo "${{ github }}"