name: Lint test and deploy on push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: test case
        run: npm run test
  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: Lint testing
        run: npm run lint
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: install Dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: deployement
        run: echo "Deploying"
      - name: Get build Artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Output Contents
        run: ls