name: Output on failure

on:
  workflow_run:
    workflows: ["Lint test and deploy on push"]
    types:
      - completed

jobs:
  info:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Output Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"